export const NUMBER_VERIFICATION_SERVICE = 'NUMBER_VERIFICATION_SERVICE';
export const SIM_SWAP_SERVICE = 'SIM_SWAP_SERVICE';
export const DEVICE_SWAP_SERVICE = 'DEVICE_SWAP_SERVICE';

export const CLIENT_REPOSITORY = 'CLIENT_REPOSITORY';